# Generated by Django 5.2 on 2025-06-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_mailuser_token"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailuser",
            options={
                "permissions": [("can_block_users", "Can block users")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
