# Generated by Django 5.2 on 2025-05-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendtry",
            name="try_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="дата и время попытки"),
        ),
    ]
