# Generated by Django 5.2 on 2025-05-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0002_alter_sendtry_try_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="addressees",
            field=models.ManyToManyField(blank=True, null=True, to="sender.addressee", verbose_name="Адресаты:"),
        ),
    ]
