# Generated by Django 5.2 on 2025-06-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0004_alter_mailing_addressees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressee",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="completed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="время завершения"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_at",
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="время запуска"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("created", "создана"), ("started", "запущена"), ("completed", "завершена")],
                default="created",
                editable=False,
                max_length=18,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="sendtry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="sendtry",
            name="response",
            field=models.TextField(blank=True, editable=False, null=True, verbose_name="ответ сервера"),
        ),
        migrations.AlterField(
            model_name="sendtry",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("success", "Успешно"), ("failure", "Не успешно")],
                editable=False,
                max_length=10,
                null=True,
                verbose_name="статус попытки",
            ),
        ),
        migrations.AlterField(
            model_name="sendtry",
            name="try_at",
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="дата и время попытки"),
        ),
        migrations.AlterField(
            model_name="sendtry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
