# Generated by Django 5.2 on 2025-06-09 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0006_addressee_owner_mailing_owner_message_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addressee",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_view_all_addressees", "Can view all addressees")],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_all_mailings", "Can view all mailings"),
                    ("can_stop_mailing", "Can stop mailing"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_view_all_messages", "Can view all messages")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
