# Generated by Django 5.2 on 2025-06-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0007_alter_addressee_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addressee",
            name="email",
            field=models.CharField(max_length=150, verbose_name="email"),
        ),
    ]
