# Generated by Django 5.2 on 2025-06-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0008_alter_addressee_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="addressees",
            field=models.ManyToManyField(null=True, to="sender.addressee", verbose_name="Адресаты:"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="sender.message", verbose_name="сообщение"
            ),
        ),
    ]
