# Generated by Django 5.2 on 2025-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0009_alter_mailing_addressees_alter_mailing_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                blank=True,
                choices=[("daily", "раз в день"), ("weekly", "раз в неделю"), ("monthly", "раз в месяц")],
                max_length=30,
                null=True,
                verbose_name="периодичность",
            ),
        ),
    ]
