# Generated by Django 5.2 on 2025-06-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender", "0010_mailing_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="addressees",
            field=models.ManyToManyField(to="sender.addressee", verbose_name="Адресаты:"),
        ),
    ]
